In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])
cons = 10
b = [11,12,13]

In [3]:
c = []
for i in range(len(a)):
    c.append(a[i] + cons)
    

In [5]:
a[[0,2]]

array([1, 3])

In [6]:
d = a + [1,2]
d

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [15]:
names = np.array(['a', 'b', 'c', 'd'])
weight = np.array([55,66,45,52])
height = np.array([140, 165, 133, 157])

In [19]:
sorted_indx = np.argsort(height)
sorted_indx

array([2, 0, 3, 1])

In [20]:
weight[sorted_indx]

array([45, 55, 52, 66])

In [21]:
names[sorted_indx]

array(['c', 'a', 'd', 'b'], dtype='<U1')